import type { MenuItem } from "./types";

/** Mock menu items — delete on integration; replace with api.ts + queries.ts. */
export const mockMenu: MenuItem[] = [
  {
    id: "m1",
    name: "Nasi Goreng Spesial",
    description: "Nasi goreng dengan telur, ayam, dan kerupuk",
    price: 28000,
    category: "makanan",
    is_available: true,
    is_deleted: false,
    created_at: "2026-06-01T03:00:00Z",
    updated_at: null,
  },
  {
    id: "m2",
    name: "Mie Ayam Bakso",
    description: "Mie ayam dengan bakso sapi dan pangsit",
    price: 25000,
    category: "makanan",
    is_available: true,
    is_deleted: false,
    created_at: "2026-06-01T03:05:00Z",
    updated_at: null,
  },
  {
    id: "m3",
    name: "Ayam Geprek Sambal Matah",
    description: "Ayam crispy dengan sambal matah segar",
    price: 32000,
    category: "makanan",
    is_available: true,
    is_deleted: false,
    created_at: "2026-06-01T03:10:00Z",
    updated_at: null,
  },
  {
    id: "m4",
    name: "Soto Ayam Lamongan",
    description: "Soto kuah bening dengan suwiran ayam",
    price: 27000,
    category: "makanan",
    is_available: false,
    is_deleted: false,
    created_at: "2026-06-01T03:12:00Z",
    updated_at: null,
  },
  {
    id: "m5",
    name: "Es Teh Manis",
    description: "Teh manis dingin segar",
    price: 8000,
    category: "minuman",
    is_available: true,
    is_deleted: false,
    created_at: "2026-06-01T03:15:00Z",
    updated_at: null,
  },
  {
    id: "m6",
    name: "Es Jeruk",
    description: "Jeruk peras asli dengan es",
    price: 12000,
    category: "minuman",
    is_available: true,
    is_deleted: false,
    created_at: "2026-06-01T03:18:00Z",
    updated_at: null,
  },
  {
    id: "m7",
    name: "Kopi Susu Gula Aren",
    description: "Espresso, susu segar, dan gula aren",
    price: 18000,
    category: "minuman",
    is_available: true,
    is_deleted: false,
    created_at: "2026-06-01T03:20:00Z",
    updated_at: null,
  },
  {
    id: "m8",
    name: "Jus Alpukat",
    description: "Alpukat segar dengan susu coklat",
    price: 20000,
    category: "minuman",
    is_available: false,
    is_deleted: false,
    created_at: "2026-06-01T03:22:00Z",
    updated_at: null,
  },
  {
    id: "m9",
    name: "Pisang Goreng Keju",
    description: "Pisang goreng crispy dengan taburan keju",
    price: 15000,
    category: "snacks",
    is_available: true,
    is_deleted: false,
    created_at: "2026-06-01T03:25:00Z",
    updated_at: null,
  },
  {
    id: "m10",
    name: "Kentang Goreng",
    description: "Kentang goreng renyah dengan saus sambal",
    price: 18000,
    category: "snacks",
    is_available: true,
    is_deleted: false,
    created_at: "2026-06-01T03:28:00Z",
    updated_at: null,
  },
  {
    id: "m11",
    name: "Lumpia Udang",
    description: "Lumpia isi udang segar, garing di luar",
    price: 22000,
    category: "snacks",
    is_available: false,
    is_deleted: false,
    created_at: "2026-06-01T03:30:00Z",
    updated_at: null,
  },
];
