"""initial schema

Revision ID: 8af2a9eb7554
Revises:
Create Date: 2026-06-07 16:59:54.090969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8af2a9eb7554'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grace_period_mins', sa.Integer(), nullable=False),
    sa.Column('avg_serve_time_mins', sa.Integer(), nullable=False),
    sa.Column('max_queue_per_day', sa.Integer(), nullable=False),
    sa.Column('is_queue_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_status_name'), 'queue_status', ['name'], unique=True)
    op.create_table('queue',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preorder_id', sa.Uuid(), nullable=True),
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=False),
    sa.Column('estimated_time', sa.DateTime(), nullable=True),
    sa.Column('is_checked_in', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Uuid(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('called_by', sa.Uuid(), nullable=True),
    sa.Column('served_by', sa.Uuid(), nullable=True),
    sa.Column('skipped_by', sa.Uuid(), nullable=True),
    sa.Column('is_requeued', sa.Boolean(), nullable=False),
    sa.Column('original_queue_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['original_queue_id'], ['queue.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['queue_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_preorder_id'), 'queue', ['preorder_id'], unique=False)
    op.create_index(op.f('ix_queue_queue_date'), 'queue', ['queue_date'], unique=False)
    op.create_index(op.f('ix_queue_queue_number'), 'queue', ['queue_number'], unique=False)
    op.create_index(op.f('ix_queue_status_id'), 'queue', ['status_id'], unique=False)
    op.create_index(op.f('ix_queue_user_id'), 'queue', ['user_id'], unique=False)
    op.create_table('queue_notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.Enum('PREPARE', 'ALMOST', 'CALLED', 'SKIPPED', 'REQUEUED', name='notificationtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_notification_customer_id'), 'queue_notification', ['customer_id'], unique=False)
    op.create_index(op.f('ix_queue_notification_queue_id'), 'queue_notification', ['queue_id'], unique=False)
    op.create_table('queue_status_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'SYSTEM', 'AUTO', name='triggertype'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_status_log_queue_id'), 'queue_status_log', ['queue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_status_log_queue_id'), table_name='queue_status_log')
    op.drop_table('queue_status_log')
    op.drop_index(op.f('ix_queue_notification_queue_id'), table_name='queue_notification')
    op.drop_index(op.f('ix_queue_notification_customer_id'), table_name='queue_notification')
    op.drop_table('queue_notification')
    op.drop_index(op.f('ix_queue_user_id'), table_name='queue')
    op.drop_index(op.f('ix_queue_status_id'), table_name='queue')
    op.drop_index(op.f('ix_queue_queue_number'), table_name='queue')
    op.drop_index(op.f('ix_queue_queue_date'), table_name='queue')
    op.drop_index(op.f('ix_queue_preorder_id'), table_name='queue')
    op.drop_table('queue')
    op.drop_index(op.f('ix_queue_status_name'), table_name='queue_status')
    op.drop_table('queue_status')
    op.drop_table('queue_settings')
    # Drop enum types created implicitly by the Enum columns above.
    sa.Enum(name='notificationtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='notificationstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='triggertype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
