events {}

http {
  server {
    listen 9090;

    location /menu/ {
      proxy_pass http://menu-preorder-service:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /queue/ {
      proxy_pass http://queue-service:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /user/ {
      proxy_pass http://user-service:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}