services:
  menu-preorder-service:
    build: ./menu-preorder-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      menu-preorder-db:
        condition: service_healthy
  
  menu-preorder-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${MENU_PREORDER_DB_USER}
      POSTGRES_PASSWORD: ${MENU_PREORDER_DB_PASSWORD}
      POSTGRES_DB: ${MENU_PREORDER_DB_NAME}
      PGPORT: ${MENU_PREORDER_DB_PORT}
    ports:
      - "${MENU_PREORDER_DB_PORT}:${MENU_PREORDER_DB_PORT}"
    volumes:
      - menu_preorder_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${MENU_PREORDER_DB_PORT} -U ${MENU_PREORDER_DB_USER} -d ${MENU_PREORDER_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  menu_preorder_data: