import type {
  Queue,
  QueueNotification,
  QueueSettings,
  QueueStatus,
  QueueStatusLog,
} from "./types";
import { STATUS_COLORS } from "./types";

const TODAY = "2026-06-08";

/** Mock queue settings — delete on integration. */
export const mockSettings: QueueSettings = {
  id: "s1",
  prefix: "A",
  grace_period_mins: 5,
  avg_serve_time_mins: 4,
  max_queue_per_day: 120,
  is_queue_open: true,
  open_time: "08:00",
  close_time: "21:00",
  created_by: "admin-1",
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-06-08T01:00:00Z",
};

/** Mock customizable statuses (id + name + color). */
export const mockStatuses: QueueStatus[] = [
  { id: "st-waiting", name: "waiting", color: STATUS_COLORS.waiting },
  { id: "st-called", name: "called", color: STATUS_COLORS.called },
  { id: "st-served", name: "served", color: STATUS_COLORS.served },
  { id: "st-skipped", name: "skipped", color: STATUS_COLORS.skipped },
  { id: "st-requeued", name: "re_queued", color: STATUS_COLORS.re_queued },
  { id: "st-cancelled", name: "cancelled", color: STATUS_COLORS.cancelled },
];

function statusId(name: string): string {
  return mockStatuses.find((s) => s.name === name)?.id ?? "st-waiting";
}

/** Mock queue entries spanning all statuses. */
export const mockQueues: Queue[] = [
  {
    id: "q1",
    user_id: "u1",
    preorder_id: "p1",
    queue_number: 1,
    queue_date: TODAY,
    estimated_time: `${TODAY}T07:30:00Z`,
    is_checked_in: true,
    checked_in_at: `${TODAY}T07:20:00Z`,
    status_id: statusId("served"),
    status_name: "served",
    called_at: `${TODAY}T07:25:00Z`,
    served_at: `${TODAY}T07:31:00Z`,
    cancelled_at: null,
    called_by: "admin-1",
    served_by: "admin-1",
    skipped_by: null,
    is_requeued: false,
    original_queue_id: null,
    created_at: `${TODAY}T07:10:00Z`,
    updated_at: `${TODAY}T07:31:00Z`,
    current_position: 0,
    estimated_wait_minutes: 0,
    customer_name: "Budi Santoso",
  },
  {
    id: "q2",
    user_id: "u2",
    preorder_id: "p2",
    queue_number: 2,
    queue_date: TODAY,
    estimated_time: `${TODAY}T07:40:00Z`,
    is_checked_in: true,
    checked_in_at: `${TODAY}T07:28:00Z`,
    status_id: statusId("called"),
    status_name: "called",
    called_at: `${TODAY}T07:36:00Z`,
    served_at: null,
    cancelled_at: null,
    called_by: "admin-1",
    served_by: null,
    skipped_by: null,
    is_requeued: false,
    original_queue_id: null,
    created_at: `${TODAY}T07:12:00Z`,
    updated_at: `${TODAY}T07:36:00Z`,
    current_position: 0,
    estimated_wait_minutes: 0,
    customer_name: "Siti Aminah",
  },
  {
    id: "q3",
    user_id: "u3",
    preorder_id: "p3",
    queue_number: 3,
    queue_date: TODAY,
    estimated_time: `${TODAY}T07:44:00Z`,
    is_checked_in: true,
    checked_in_at: `${TODAY}T07:30:00Z`,
    status_id: statusId("waiting"),
    status_name: "waiting",
    called_at: null,
    served_at: null,
    cancelled_at: null,
    called_by: null,
    served_by: null,
    skipped_by: null,
    is_requeued: false,
    original_queue_id: null,
    created_at: `${TODAY}T07:15:00Z`,
    updated_at: `${TODAY}T07:30:00Z`,
    current_position: 1,
    estimated_wait_minutes: 4,
    customer_name: "Andi Wijaya",
  },
  {
    id: "q4",
    user_id: "u4",
    preorder_id: null,
    queue_number: 4,
    queue_date: TODAY,
    estimated_time: `${TODAY}T07:48:00Z`,
    is_checked_in: false,
    checked_in_at: null,
    status_id: statusId("waiting"),
    status_name: "waiting",
    called_at: null,
    served_at: null,
    cancelled_at: null,
    called_by: null,
    served_by: null,
    skipped_by: null,
    is_requeued: false,
    original_queue_id: null,
    created_at: `${TODAY}T07:18:00Z`,
    updated_at: `${TODAY}T07:18:00Z`,
    current_position: 2,
    estimated_wait_minutes: 8,
    customer_name: "Dewi Lestari",
  },
  {
    id: "q5",
    user_id: "u5",
    preorder_id: "p5",
    queue_number: 5,
    queue_date: TODAY,
    estimated_time: `${TODAY}T07:52:00Z`,
    is_checked_in: false,
    checked_in_at: null,
    status_id: statusId("skipped"),
    status_name: "skipped",
    called_at: `${TODAY}T07:40:00Z`,
    served_at: null,
    cancelled_at: null,
    called_by: "admin-1",
    served_by: null,
    skipped_by: "admin-1",
    is_requeued: false,
    original_queue_id: null,
    created_at: `${TODAY}T07:20:00Z`,
    updated_at: `${TODAY}T07:46:00Z`,
    current_position: 0,
    estimated_wait_minutes: 0,
    customer_name: "Rizky Pratama",
  },
  {
    id: "q6",
    user_id: "u6",
    preorder_id: null,
    queue_number: 6,
    queue_date: TODAY,
    estimated_time: `${TODAY}T07:56:00Z`,
    is_checked_in: true,
    checked_in_at: `${TODAY}T07:35:00Z`,
    status_id: statusId("waiting"),
    status_name: "waiting",
    called_at: null,
    served_at: null,
    cancelled_at: null,
    called_by: null,
    served_by: null,
    skipped_by: null,
    is_requeued: false,
    original_queue_id: null,
    created_at: `${TODAY}T07:24:00Z`,
    updated_at: `${TODAY}T07:35:00Z`,
    current_position: 3,
    estimated_wait_minutes: 12,
    customer_name: "Maya Putri",
  },
  {
    id: "q7",
    user_id: "u7",
    preorder_id: "p7",
    queue_number: 7,
    queue_date: TODAY,
    estimated_time: null,
    is_checked_in: false,
    checked_in_at: null,
    status_id: statusId("cancelled"),
    status_name: "cancelled",
    called_at: null,
    served_at: null,
    cancelled_at: `${TODAY}T07:30:00Z`,
    called_by: null,
    served_by: null,
    skipped_by: null,
    is_requeued: false,
    original_queue_id: null,
    created_at: `${TODAY}T07:26:00Z`,
    updated_at: `${TODAY}T07:30:00Z`,
    current_position: 0,
    estimated_wait_minutes: 0,
    customer_name: "Joko Susilo",
  },
  {
    id: "q8",
    user_id: "u5",
    preorder_id: "p5",
    queue_number: 8,
    queue_date: TODAY,
    estimated_time: `${TODAY}T08:04:00Z`,
    is_checked_in: true,
    checked_in_at: `${TODAY}T07:50:00Z`,
    status_id: statusId("re_queued"),
    status_name: "re_queued",
    called_at: null,
    served_at: null,
    cancelled_at: null,
    called_by: null,
    served_by: null,
    skipped_by: null,
    is_requeued: true,
    original_queue_id: "q5",
    created_at: `${TODAY}T07:48:00Z`,
    updated_at: `${TODAY}T07:50:00Z`,
    current_position: 4,
    estimated_wait_minutes: 16,
    customer_name: "Rizky Pratama",
  },
];

/** Status logs for queue q1 (the served one) — audit trail demo. */
export const mockStatusLogs: QueueStatusLog[] = [
  {
    id: "l1",
    queue_id: "q1",
    previous_status: null,
    new_status: "waiting",
    triggered_by: null,
    trigger_type: "system",
    notes: "Antrian dibuat dari pre-order",
    created_at: `${TODAY}T07:10:00Z`,
  },
  {
    id: "l2",
    queue_id: "q1",
    previous_status: "waiting",
    new_status: "called",
    triggered_by: "admin-1",
    trigger_type: "admin",
    notes: "Dipanggil oleh admin",
    created_at: `${TODAY}T07:25:00Z`,
  },
  {
    id: "l3",
    queue_id: "q1",
    previous_status: "called",
    new_status: "served",
    triggered_by: "admin-1",
    trigger_type: "admin",
    notes: "Selesai dilayani",
    created_at: `${TODAY}T07:31:00Z`,
  },
];

/** Notifications for queue q1. */
export const mockNotifications: QueueNotification[] = [
  {
    id: "n1",
    name: null,
    queue_id: "q1",
    customer_id: "u1",
    notification_type: "confirmation",
    status: "sent",
    message: "Antrian A001 berhasil dibuat. Sampai jumpa!",
    sent_at: `${TODAY}T07:10:05Z`,
    failed_reason: null,
    created_at: `${TODAY}T07:10:00Z`,
  },
  {
    id: "n2",
    name: null,
    queue_id: "q1",
    customer_id: "u1",
    notification_type: "prepare",
    status: "sent",
    message: "Bersiap ya, tinggal 3 antrian lagi sebelum giliranmu.",
    sent_at: `${TODAY}T07:18:00Z`,
    failed_reason: null,
    created_at: `${TODAY}T07:18:00Z`,
  },
  {
    id: "n3",
    name: null,
    queue_id: "q1",
    customer_id: "u1",
    notification_type: "almost",
    status: "sent",
    message: "Sebentar lagi giliranmu! Mohon mendekat ke counter.",
    sent_at: `${TODAY}T07:23:00Z`,
    failed_reason: null,
    created_at: `${TODAY}T07:23:00Z`,
  },
  {
    id: "n4",
    name: null,
    queue_id: "q1",
    customer_id: "u1",
    notification_type: "called",
    status: "sent",
    message: "Nomor A001 dipanggil. Silakan menuju counter.",
    sent_at: `${TODAY}T07:25:00Z`,
    failed_reason: null,
    created_at: `${TODAY}T07:25:00Z`,
  },
];

/** Convenience: the queue used for the customer ticket demo. */
export const mockCustomerQueue: Queue =
  mockQueues.find((q) => q.id === "q3") ?? mockQueues[0];
