import uuid
from uuid import UUID
from datetime import datetime
from typing import Optional, List
from enum import Enum
from sqlmodel import SQLModel, Field, Relationship, Column, DateTime, func
from app.menu.models import Menu

class OrderItemBase(SQLModel):
    menu_item_id: UUID = Field(foreign_key="menu_items.id", schema_extra={"examples": [str(uuid.uuid4())]})
    quantity: int = Field(gt=0, schema_extra={"examples": [1]})

class OrderItem(OrderItemBase, table=True):
    __tablename__ = "order_items"

    id: UUID = Field(default_factory=uuid.uuid4, primary_key=True, index=True)
    order_id: UUID = Field(foreign_key="orders.id")
    subtotal: float = Field(gt=0, schema_extra={"examples": [30000.0]})

    order: "Order" = Relationship(back_populates="items")
    menu: Menu = Relationship()


class OrderBase(SQLModel):
    notes: Optional[str] = Field(default=None, max_length=255, schema_extra={"examples": ["Pedas, tanpa sayur"]})

class OrderStatus(str, Enum):
    PENDING = "pending"
    CONFIRMED = "confirmed"
    CANCELLED = "cancelled"

class Order(OrderBase, table=True):
    __tablename__ = "orders"

    id: UUID = Field(default_factory=uuid.uuid4, primary_key=True, index=True)
    user_id: UUID = Field(schema_extra={"examples": [str(uuid.uuid4())]})
    queue_number: Optional[int] = Field(default=None, nullable=True, schema_extra={"examples": [1]})
    total_price: float = Field(schema_extra={"examples": [30000.0]})
    status: OrderStatus = Field(default=OrderStatus.PENDING, schema_extra={"examples": [OrderStatus.PENDING]})
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), onupdate=func.now(), nullable=True)
    )

    items: List[OrderItem] = Relationship(back_populates="order")

class OrderItemCreate(OrderItemBase):
    pass

class OrderCreate(OrderBase):
    items: List[OrderItemCreate] = Field(schema_extra={"examples": [[{"menu_item_id": str(uuid.uuid4()), "quantity": 1}]]})

class OrderUpdate(SQLModel):
    status: Optional[OrderStatus] = Field(default=None, description="New status of the order")
    queue_number: Optional[int] = Field(default=None, description="Queue number generated by the queue service")

class OrderItemResponse(SQLModel):
    menu_item_id: UUID
    quantity: int
    subtotal: float
    menu: Optional[Menu] = None

class OrderResponse(OrderBase):
    id: UUID
    queue_number: Optional[int] = None
    user_id: UUID
    total_price: float
    status: OrderStatus
    created_at: datetime
    updated_at: Optional[datetime] = None
    items: List[OrderItemResponse] = []
